### ISSUE TITLE
SDK 34 (Android 14). Error in com.zegocloud.uikit.flutter.live_audio_room.ForegroundService.onStartCommand(ForegroundService.kt:65)

### ISSUE THREAD

**Issue by mamine3004** [ZEGOCLOUD/zego_uikit_prebuilt_live_audio_room_example_flutter#2]
I am getting this error:
```
E/AndroidRuntime(11450): FATAL EXCEPTION: main
E/AndroidRuntime(11450): Process: com.zegocloud.uikit.flutter.live_audio_room, PID: 11450
E/AndroidRuntime(11450): java.lang.RuntimeException: Unable to start service com.zegocloud.uikit.flutter.live_audio_room.ForegroundService@ddbb5c7 with Intent { cmp=com.zegocloud.uikit.flutter.live_audio_room/.ForegroundService }: java.lang.SecurityException: Starting FGS with type microphone callerApp=ProcessRecord{ec639cd 11450:com.zegocloud.uikit.flutter.live_audio_room/u0a359} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MICROPHONE] any of the permissions allOf=false [android.permission.CAPTURE_AUDIO_HOTWORD, android.permission.CAPTURE_AUDIO_OUTPUT, android.permission.CAPTURE_MEDIA_OUTPUT, android.permission.CAPTURE_TUNER_AUDIO_INPUT, android.permission.CAPTURE_VOICE_COMMUNICATION_OUTPUT, android.permission.RECORD_AUDIO]  and the app must be in the eligible state/exemptions to access the foreground only permission
E/AndroidRuntime(11450): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5286)
E/AndroidRuntime(11450): 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
E/AndroidRuntime(11450): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531)
E/AndroidRuntime(11450): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(11450): 	at android.os.Looper.loopOnce(Looper.java:230)
E/AndroidRuntime(11450): 	at android.os.Looper.loop(Looper.java:319)
E/AndroidRuntime(11450): 	at android.app.ActivityThread.main(ActivityThread.java:8893)
E/AndroidRuntime(11450): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11450): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
E/AndroidRuntime(11450): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
E/AndroidRuntime(11450): Caused by: java.lang.SecurityException: Starting FGS with type microphone callerApp=ProcessRecord{ec639cd 11450:com.zegocloud.uikit.flutter.live_audio_room/u0a359} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MICROPHONE] any of the permissions allOf=false [android.permission.CAPTURE_AUDIO_HOTWORD, android.permission.CAPTURE_AUDIO_OUTPUT, android.permission.CAPTURE_MEDIA_OUTPUT, android.permission.CAPTURE_TUNER_AUDIO_INPUT, android.permission.CAPTURE_VOICE_COMMUNICATION_OUTPUT, android.permission.RECORD_AUDIO]  and the app must be in the eligible state/exemptions to access the foreground only permission
E/AndroidRuntime(11450): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
E/AndroidRuntime(11450): 	at android.os.Parcel.createException(Parcel.java:3053)
E/AndroidRuntime(11450): 	at android.os.Parcel.readException(Parcel.java:3036)
E/AndroidRuntime(11450): 	at android.os.Parcel.readException(Parcel.java:2978)
E/AndroidRuntime(11450): 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7214)
E/AndroidRuntime(11450): 	at android.app.Service.startForeground(Service.java:862)
E/AndroidRuntime(11450): 	at com.zegocloud.uikit.flutter.live_audio_room.ForegroundService.onStartCommand(ForegroundService.kt:65)
E/AndroidRuntime(11450): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268)
E/AndroidRuntime(11450): 	... 9 more
E/AndroidRuntime(11450): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(11450): 	at com.android.server.am.ActiveServices.validateForegroundServiceType(ActiveServices.java:2729)
E/AndroidRuntime(11450): 	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2440)
E/AndroidRuntime(11450): 	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1785)
E/AndroidRuntime(11450): 	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:15875)
E/AndroidRuntime(11450): 	at android.app.IActivityManager$Stub.onTransact$setServiceForeground$(IActivityManager.java:11873)
E/AndroidRuntime(11450): 
Error connecting to the service protocol: failed to connect to http://127.0.0.1:50893/73ooyhqzY8s=/
```
I think it's because of permission.so I did some of changes:
in main.dart:
```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await requestPermissions();
  final navigatorKey = GlobalKey<NavigatorState>();
  ZegoUIKit().initLog().then((value) {
    runApp(MyApp(
      navigatorKey: navigatorKey,
    ));
  });
}

Future<void> requestPermissions() async {
  PermissionStatus microphoneStatus = await Permission.microphone.request();

  if (microphoneStatus.isGranted) {
    startForegroundNotificationService();
  } else {
    // Handle denied permissions
    print('Permissions not granted.');
  }
}


const platform = MethodChannel('com.zegocloud.uikit.flutter/live_audio_room');

Future<void> startForegroundNotificationService() async {
  try {
    await platform.invokeMethod('startForegroundService');
  } on PlatformException catch (e) {
    print("Failed to start service: '${e.message}'.");
  }
}
```
and in MainActivity.kt
```kotlin
package com.zegocloud.uikit.flutter.live_audio_room

import android.content.Intent
import android.os.Bundle
import androidx.core.content.ContextCompat
import io.flutter.embedding.android.FlutterActivity
import io.flutter.plugin.common.MethodChannel

class MainActivity: FlutterActivity() {
    private val CHANNEL = "com.zegocloud.uikit.flutter/live_audio_room"

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // Make sure flutterEngine is not null before creating the MethodChannel
        flutterEngine?.let {
            MethodChannel(it.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler { call, result ->
                if (call.method == "startForegroundService") {
                    startForegroundNotificationService()
                    result.success(null)
                } else {
                    result.notImplemented()
                }
            }
        }
    }

    // Start the foreground service
    private fun startForegroundNotificationService() {
        ContextCompat.startForegroundService(
                this, Intent(this, ForegroundService::class.java)
        )
    }
}

```
it works now after this modification.

**Comment by rimon1210** [comment]
class LivePage extends StatefulWidget {
  const LivePage({
    Key? key,
    required this.roomID,
    this.isHost = false,
  }) : super(key: key);

  final String roomID;
  final bool isHost;

  @override
  State<LivePage> createState() => _LivePageState();
}

class _LivePageState extends State<LivePage> {
  final isSeatClosedNotifier = ValueNotifier<bool>(false);
  final isRequestingNotifier = ValueNotifier<bool>(false);

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: ZegoUIKitPrebuiltLiveAudioRoom(
          appID: YourSecret.appID,
          appSign: YourSecret.appSign,
          userID: userID,
          userName: 'user_$userID',
          roomID: widget.roomID,
          events: ZegoUIKitPrebuiltLiveAudioRoomEvents(
            seat: ZegoLiveAudioRoomSeatEvents(
              onClosed: () {
                isSeatClosedNotifier.value = true;
              },
              onOpened: () {
                isSeatClosedNotifier.value = false;
              },
              onChanged: (
                Map<int, ZegoUIKitUser> takenSeats,
                List<int> untakenSeats,
              ) {
                if (isRequestingNotifier.value) {
                  if (takenSeats.values
                      .map((e) => e.id)
                      .toList()
                      .contains(userID)) {
                    /// on the seat now
                    isRequestingNotifier.value = false;
                  }
                }
              },
              host: ZegoLiveAudioRoomSeatHostEvents(),
              audience: ZegoLiveAudioRoomSeatAudienceEvents(
                onTakingRequestFailed: () {
                  isRequestingNotifier.value = false;
                },
                onTakingRequestRejected: () {
                  isRequestingNotifier.value = false;
                },
              ),
            ),
          ),
          config: (widget.isHost
              ? ZegoUIKitPrebuiltLiveAudioRoomConfig.host()
              : ZegoUIKitPrebuiltLiveAudioRoomConfig.audience())

            ///  Remove the button that is used for the audience to apply to take a seat.
            ..bottomMenuBar.audienceButtons = const [
              ZegoLiveAudioRoomMenuBarButtonName.showMemberListButton,
            ]

            /// Add custom button.
            ..bottomMenuBar.audienceExtendButtons = [
              connectButton(),
            ]),
    );
  }

  Widget connectButton() {
    return ValueListenableBuilder<bool>(
      valueListenable: isSeatClosedNotifier,
      builder: (context, isSeatClosed, _) {
        return isSeatClosed
            ? ValueListenableBuilder<bool>(
                valueListenable: isRequestingNotifier,
                builder: (context, isRequesting, _) {
                  return isRequesting
                      ? ElevatedButton(
                          onPressed: () {
                            ZegoUIKitPrebuiltLiveAudioRoomController()
                                .seat
                                .audience
                                .cancelTakingRequest()
                                .then((result) {
                              isRequestingNotifier.value = false;
                            });
                          },
                          child: const Text('Cancel'),
                        )
                      : ElevatedButton(
                          onPressed: () {
                            ZegoUIKitPrebuiltLiveAudioRoomController()
                                .seat
                                .audience
                                .applyToTake()
                                .then((result) {
                              isRequestingNotifier.value = result;
                            });
                          },
                          child: const Text('Request'),
                        );
                },
              )
            : Container();
      },
    );
  }
}
